version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: e-com
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db 